"""unique username

Revision ID: 1ab2d3cbf573
Revises: 3268ff181881
Create Date: 2026-01-12 11:39:54.656713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab2d3cbf573'
down_revision: Union[str, Sequence[str], None] = '3268ff181881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_tenant_username', 'users', ['site_config_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_tenant_username', 'users', type_='unique')
    # ### end Alembic commands ###
