"""removed visit limits

Revision ID: 3268ff181881
Revises: c95373adf116
Create Date: 2026-01-09 18:04:13.312053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3268ff181881'
down_revision: Union[str, Sequence[str], None] = 'c95373adf116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_config', 'search_rate_limit')
    op.drop_column('site_config', 'booking_rate_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_config', sa.Column('booking_rate_limit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site_config', sa.Column('search_rate_limit', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
