"""second one for the limits max bookiing

Revision ID: c95373adf116
Revises: 3359962a8ac3
Create Date: 2026-01-08 12:42:19.274255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95373adf116'
down_revision: Union[str, Sequence[str], None] = '3359962a8ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_config', sa.Column('max_booking_days', sa.Integer(), nullable=True))
    op.add_column('site_config', sa.Column('max_rooms_per_booking', sa.Integer(), nullable=True))
    op.add_column('site_config', sa.Column('search_rate_limit', sa.String(), nullable=True))
    op.add_column('site_config', sa.Column('booking_rate_limit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_config', 'booking_rate_limit')
    op.drop_column('site_config', 'search_rate_limit')
    op.drop_column('site_config', 'max_rooms_per_booking')
    op.drop_column('site_config', 'max_booking_days')
    # ### end Alembic commands ###
